### ISSUE TITLE
No preview for blocks extending/replacing 'columns' block

### ISSUE THREAD

**Issue by ghost** [youngcut/kirby-column-blocks#5]
Hey there,
when creating eg `blueprints/blocks/text.columns.yml` like this ..

```yml
extends: blocks/columns
fields:
  layout:
    layouts:
      - "1/2, 1/2"
      - "1/3, 1/3, 1/3"
      - "1/4, 1/4, 1/4, 1/4"
    fieldsets:
      - heading
      - text
      - image
```

.. then there's no preview - here I created two normal `columns` blocks and one `text.columns` (see above), and they are rendered like this:

<img width="950" alt="Screenshot 2023-02-19 at 09 23 09" src="https://user-images.githubusercontent.com/122524301/219937250-f9b9d1ae-c9f3-40ff-ba84-c8f5f8e37636.png">

I may edit its contents, but only by clicking on the pencil, so I guess that's not desired behavior 😉 

Cheers,
CHE1RON

PHP: 8.0.28
Kirby: 3.9.1
